name: Update RSS Feeds

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual run to test

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permission to push back to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Facebook Scraper
        run: python scraper.py

      - name: Commit and Push XML files
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add *.xml
          # Check if there are changes before committing
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update RSS Feeds [$(date)]"
            git push
          fi
